### ISSUE TITLE
Attributes not readable with ncdump?

### ISSUE THREAD

**Issue by vanne02135** [h5netcdf/h5netcdf#14]
The file written from example code is not readable by ncdump. 

``` python
import h5netcdf
import numpy as np

with h5netcdf.File('mydata.nc', 'w') as f:
    f.dimensions = {'x': 5}
    v = f.create_variable('hello', ('x',), float)
    v[:] = np.ones(5)

with h5netcdf.File("mydata_attr.nc", "w") as f:
    f.dimensions = {"x": 5}
    v = f.create_variable("hello", ("x",), 'f8')
    v[:] = np.ones(5)
    v.attrs["test"] = "hello"
```

```
ncdump: mydata_attr.nc: NetCDF: Can't open HDF5 attribute
```

but without the attribute (mydata.nc), it displays just fine. 

```
netcdf mydata {
dimensions:
    x = 5 ;
variables:
    double hello(x) ;
data:

 hello = 1, 1, 1, 1, 1 ;
}
```

Is there a workaround for this?

**Comment by shoyer** [comment]
Have you tried updating ncdump and/or the netCDF library? This works for me:
```
$ ncdump mydata_attr.nc
netcdf mydata_attr {
dimensions:
	x = 5 ;
variables:
	double hello(x) ;
		string hello:test = "hello" ;
data:

 hello = 1, 1, 1, 1, 1 ;
}
```

**Comment by shoyer** [comment]
To set some context here, the issue is that by default h5netcdf will write attributes as variable length strings by default, because that's what h5py does. For maximum compatibility, you probably don't want to use variable length strings and may want to use `np.string_`. The h5py docs have some useful guidance here:
http://h5py.readthedocs.org/en/latest/strings.html#how-to-store-text-strings

**Comment by vanne02135** [comment]
I'm trying to read the files with Matlab. What version of netCDF do you use? Thanks for the np.string_ tip!

**Comment by shoyer** [comment]
Looks like I'm using netcdf 4.3.3.1, installed via brew on OS X.

**Comment by kmuehlbauer** [comment]
The OP's example works with recent hdf5/netcdf libraries and their python bindings. Please re-open if appropriate.
