### ISSUE TITLE
List of Functions

### ISSUE THREAD

**Issue by gamaanderson** [h5netcdf/h5netcdf#8]
Hello @shoyer 

Let me congratulate you again for you work, I really think it's an important one and I hope you got the recognition.

That being said I would like to suggest that you add a list of the supported features, in especial for the legacyapi. NetCDF4 has lots of features and new ones are constantly added, so you can can not guaranty to support "most of the features of the netCDF interface". In special in NetCDF4, createVariable has an argument `endian`, also NetCDF4 has the [mask and scale](http://netcdf4-python.googlecode.com/svn/trunk/docs/netCDF4.Variable-class.html#set_auto_maskandscale) feature, I may be wrong, but it seems like h5netcdf don't have those features.

**Comment by shoyer** [comment]
Thanks -- I'll do my best to get that together.

As for `endian`, h5py does not appear to expose this feature, so it wasn't an option to include.

And as for mask and scale, I intentionally omitted -- this is the sort of feature that is better handled (in my opinion) in client libraries, because there are multiple options for how the unmasked/scaled data should be stored (e.g., using masked array or normal numpy arrays of float marking missing values with NaN).

**Comment by shoyer** [comment]
As a step toward this, I updated the readme with a list of functionality that I know we don't support.

**Comment by kmuehlbauer** [comment]
As this is summarized in the [README](https://github.com/h5netcdf/h5netcdf/blob/master/README.rst) I'll close this.
