### ISSUE TITLE
Inconsistent attribute handling between netcdf4 and h5netcdf

### ISSUE THREAD

**Issue by rabernat** [h5netcdf/h5netcdf#94]
I have found a netCDF file that cannot be decoded by xarray via the h5netcdf engine but CAN be decoded via netCDF4. 

This file will reproduce the bug
```
! wget 'https://esgf-world.s3.amazonaws.com/CMIP6/CMIP/IPSL/IPSL-CM6A-LR/abrupt-4xCO2/r1i1p1f1/Lmon/cLeaf/gr/v20190118/cLeaf_Lmon_IPSL-CM6A-LR_abrupt-4xCO2_r1i1p1f1_gr_185001-214912.nc'
```

```python
import netCDF4
import h5netcdf.legacyapi as netCDF4_h5

local_path = "cLeaf_Lmon_IPSL-CM6A-LR_abrupt-4xCO2_r1i1p1f1_gr_185001-214912.nc"
with netCDF4_h5.Dataset(local_path, mode='r') as ncfile:
    print('h5netcdf:', ncfile['cLeaf'].getncattr("coordinates"))
with netCDF4.Dataset(local_path, mode='r') as ncfile:
    #assert "coordinates" not in ncfile['cLeaf'].attrs
    print('netCDF4:', ncfile['cLeaf'].getncattr("coordinates"))
```

```
h5netcdf: Empty(dtype=dtype('S1'))
netCDF4: 
```

As we can see, we get an empty string `''` in netCDF4 but a `<class 'h5py._hl.base.Empty'>` object from h5netcdf. This weird attribute prevents xarray from decoding the dataset.

**Environment**:

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]
python-bits: 64
OS: Linux
OS-release: 4.19.150+
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.6
libnetcdf: 4.7.4

xarray: 0.17.0
pandas: 1.2.3
numpy: 1.20.2
scipy: 1.6.2
netCDF4: 1.5.6
pydap: installed
h5netcdf: 0.10.0
h5py: 3.1.0
Nio: None
zarr: 2.7.0
cftime: 1.4.1
nc_time_axis: 1.2.0
PseudoNetCDF: None
rasterio: 1.2.1
cfgrib: 0.9.8.5
iris: None
bottleneck: 1.3.2
dask: 2021.03.1
distributed: 2021.03.1
matplotlib: 3.3.4
cartopy: 0.18.0
seaborn: None
numbagg: None
pint: 0.17
setuptools: 49.6.0.post20210108
pip: 20.3.4
conda: None
pytest: None
IPython: 7.22.0
sphinx: None

</details>

xref https://github.com/pangeo-forge/pangeo-forge/issues/105, https://github.com/pydata/xarray/issues/5172

**Comment by kmuehlbauer** [comment]
@rabernat Thanks for raising this.

Below is the h5dump of the attribute in question.

```
ATTRIBUTE "coordinates" {
         DATATYPE  H5T_STRING {
            STRSIZE 1;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  NULL
      }
```
I do not immediately see how much will be involved to implement this conversion (`Empty()`->`''` and `''`-> `Empty()`). 

Please find more context in https://github.com/h5py/h5py/issues/279 and a simple fix for the reading part in https://github.com/jupyterlab/jupyterlab-hdf5/pull/79.

**Comment by kmuehlbauer** [comment]
@rabernat @shoyer 

So, there seems to be an easy fix in the h5netcdf `Attributes` class:

```python
    def __getitem__(self, key):
        import h5py
        if key in _HIDDEN_ATTRS:
            raise KeyError(key)
        if isinstance(self._h5attrs[key], h5py.Empty):
            if h5py.check_string_dtype(self._h5attrs[key].dtype):
                return np.array("", np.dtype(self._h5attrs[key].dtype)).item()
        return self._h5attrs[key]
```

This will return an empty `np.bytes` instead of `h5py.Empty()`. This is then correctly decoded in xarray's `h5netcdf` backend. Complete and transparent roundtripping of `h5py.Empty()` will need much more thought. The major problem is how to keep consistent with `h5py` and be in line with xarray in the same time. YAKA (Yet another keyword argument)? If we would not like to open that can of worms, it would really be easier to fix that on the xarray side (sorry @rabernat for towing you here):

```python
def maybe_decode_bytes(txt):
    if isinstance(txt, bytes):
        return txt.decode("utf-8")
    elif isinstance(txt, h5py.Empty):
        return ""  
    else:
        return txt
```
I can create PR for any of the proposed solutions and really appreciate your input.

**Comment by shoyer** [comment]
Ryan, do you know by chance how this netCDF file was made? Even the low level netCDF C interface requires providing attribute values when creating them, so I'm wondering if this might be better considered a corrupted netCFF file. Either way, it would be nice to support reading them as empty strings (and to raise an error about invalid netCFF files if a user tries to create such NULL attributes).

**Comment by rabernat** [comment]
It was made by IPSL as part of their CMIP6 data request. That's all I know. Could dig further if it would help.

**Comment by shoyer** [comment]
Interesting. It looks like netCDF-C uses this strategy for writing length 0 fixed-length character attributes (`NC_CHAR`):
https://github.com/Unidata/netcdf-c/blob/9bf69804a131b5430a02f7ff6b787e7f13fe93fa/libhdf5/nc4hdf.c#L481-L485

However, this logic is side-stepped by netCDF4-Python, which just writes a null byte `\x00` instead:
https://github.com/Unidata/netcdf4-python/blob/9dfa48dac5df90d2563f82ed5ed33bf41e76ff06/src/netCDF4/_netCDF4.pyx#L1626

h5py uses a variant of this strategy: it writes a null byte, but marks the string data type as "null padded" rather than "null terminated". Technically, a length 1 character string is both null padded _and_ null terminated, so I guess this is fine.

For reading, the netCDF-C library seems to be perfectly happy with all of these options. As far as I can tell, it treats them identically.

I'm not concerned about full compatibility with h5py here. Null values in `DATASPACE` are a niche feature that isn't part of the netCDF data model and that nothing has asked for. I think it's much more important to support reading arbitrary netCDF files.

To that end, here are my suggestions:
- When reading, return empty bytes (`b''` ) when we encounter `h5py.Empty` with `string='S1'`. This is consistent with netCDF-C. In other cases, it doesn't really matter.
- When writing empty character strings, we _could_ write another `h5py.Empty` object (like netCDF-C), but given that netCDF-C is equally happy with what h5py already does I'm not sure it's worth the trouble.
